export const testData = [
  {
    firstName: "Jessica",
    lastName: "Anderson",
    email: "jessica.anderson@example.com",
    gender: "Female",
    date: "2023-04-10",
  },
  {
    firstName: "David",
    lastName: "Taylor",
    email: "david.taylor@example.com",
    gender: "Male",
    date: "2023-03-28",
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah.wilson@example.com",
    gender: "Female",
    date: "2023-03-12",
  },
  {
    firstName: "Michael",
    lastName: "Davis",
    email: "michael.davis@example.com",
    gender: "Male",
    date: "2023-03-01",
  },
  {
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    gender: "Female",
    date: "2023-02-15",
  },
  {
    firstName: "Robert",
    lastName: "Smith",
    email: "robert.smith@example.com",
    gender: "Male",
    date: "2023-02-03",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    gender: "Female",
    date: "2023-01-15",
  },
];
